apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-web-server.fullname" . }}
  labels:
    {{- include "my-web-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-web-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-web-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}  # Ensure this matches the port in the values.yaml
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          envFrom:
            - configMapRef:
                name: vault-secrets
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
