apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.secretPath }}"
type: Opaque
data:
  password: {{ .Values.password | b64enc }}
