apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.secretPath }}"
type: Opaque
data:
  password: {{ .Values.vaultPassword | b64enc | quote }}
